ec_site/config/routes.rb
# Rails.application.routes.draw do
#   get "orders/new"
#   get "carts/show"
#   get "products/index"
#   get "products/show"
#   root "users/sessions#new"

#   namespace :admins do
#     get "tags/index"
#     get "tags/new"
#     get "tags/create"
#     get "tags/destroy"
#     get "books/index"
#     get "books/new"
#     get "books/create"
#     get "books/show"
#     get "books/edit"
#     get "books/update"
#     get "books/destroy"
#     get "sessions/new"
#     get  "sign_in",  to: "sessions#new"
#     post "sign_in",  to: "sessions#create"
#     delete "sign_out", to: "sessions#destroy"
#     resources :books
#     resources :tags, only: [:index, :new, :create, :destroy]
#   end

#   namespace :users do
#     get "mypages/show"
#     get "registrations/new"
#     get  "sign_in",  to: "sessions#new"
#     post "sign_in",  to: "sessions#create"
#     delete "sign_out", to: "sessions#destroy"
#     get  "sign_up",  to: "registrations#new"
#     post "sign_up",  to: "registrations#create"
#     resources :mypages, only: [:show]
#   end

#   resources :products, only: [:index, :show]
#   resource  :cart, only: [:show, :destroy] do
#     post :add_item
#     delete :remove_item
#   end
#   resources :orders, only: [:new, :create] do
#     post :confirm, on: :collection
#     get  :complete, on: :member
#   end
# end
Rails.application.routes.draw do
  get "orders/new"
  get "carts/show"
  get "products/index"
  get "products/show"
  root "users/sessions#new"

  namespace :admins do
    get  "sign_in",  to: "sessions#new"
    post "sign_in",  to: "sessions#create"
    delete "sign_out", to: "sessions#destroy", as: :sign_out

    resources :books
    resources :tags, only: [:index, :new, :create, :destroy]
  end

  namespace :users do
    get  "sign_in",  to: "sessions#new"
    post "sign_in",  to: "sessions#create"
    delete "sign_out", to: "sessions#destroy", as: :sign_out

    get  "sign_up",  to: "registrations#new"
    post "sign_up",  to: "registrations#create"

    resources :mypages, only: [:show]
  end

  resources :products, only: [:index, :show]

  resource :cart, only: [:show, :destroy] do
    post :add_item
    delete :remove_item
  end

  resources :orders, only: [:new, :create] do
    post :confirm, on: :collection
    get  :complete, on: :member
  end
end

ec_site/app/models/admin.rb
class Admin < ApplicationRecord
end

ec_site/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ec_site/app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
end

ec_site/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

ec_site/app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :book
  belongs_to :cart
end

ec_site/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
end

ec_site/app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :book
end

ec_site/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :books, through: :taggings
end

ec_site/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

ec_site/app/models/user.rb
class User < ApplicationRecord
  has_many :orders, dependent: :destroy
end

ec_site/app/controllers/admins/books_controller.rb
class Admins::BooksController < ApplicationController

  def require_admin
    redirect_to admins_sign_in_path unless admin_signed_in?
  end


  def index
    @books = Book.order(id: :asc)
  end

  def new
    @book = Book.new
    @tags = Tag.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      attach_image
      assign_tags
      redirect_to admins_book_path(@book)
    else
      @tags = Tag.all
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    @tags = Tag.all
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      attach_image
      assign_tags
      redirect_to admins_book_path(@book)
    else
      @tags = Tag.all
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to admins_books_path
  end

  private

  def require_admin
    redirect_to admins_sign_in_path unless admin_signed_in?
  end

  def book_params
    params.require(:book).permit(:book_name, :author_name, :issue_date, :product_display, :price, :status)
  end

  def attach_image
    if params[:book][:image].present?
      @book.image.attach(params[:book][:image])
    end
  end

  def assign_tags
    ids = Array(params[:book][:tag_ids]).reject(&:blank?)
    @book.taggings.destroy_all
    ids.each { |tid| @book.taggings.create(tag_id: tid) }
  end
end

ec_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_admin, :admin_signed_in?, :current_user, :user_signed_in?, :current_cart

  def current_admin
    @current_admin ||= Admin.find_by(id: session[:admin_id])
  end

  def admin_signed_in?
    current_admin.present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    current_user.present?
  end

  def current_cart
    session[:cart_session_id] ||= SecureRandom.hex(10)
    Cart.find_or_create_by(session_id: session[:cart_session_id])
  end
end

ec_site/app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :require_login

  def show
    @cart = current_cart
    @line_items = @cart.line_items.includes(:book)
  end

  def destroy
    current_cart.line_items.destroy_all
    redirect_to products_path, notice: "カートが空になりました"
  end

  def add_item
    book = Book.find(params[:book_id])
    qty = params[:quantity].to_i
    item = current_cart.line_items.find_or_initialize_by(book_id: book.id)
    item.quantity = item.quantity.to_i + qty
    item.price = book.price
    item.save
    redirect_to cart_path
  end

  def remove_item
    item = current_cart.line_items.find_by(id: params[:line_item_id])
    item&.destroy
    redirect_to cart_path
  end

  private

  def require_login
    redirect_to users_sign_in_path unless user_signed_in?
  end
end

ec_site/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_login

  def new
    @cart = current_cart
    @line_items = @cart.line_items.includes(:book)
    @order = Order.new
  end

  def confirm
    @cart = current_cart
    @line_items = @cart.line_items.includes(:book)
    @address = params[:delivery_address]
    @total = @line_items.sum { |i| i.price * i.quantity }
    render :confirm
  end

  def create
    cart = current_cart
    line_items = cart.line_items.includes(:book)
    total = line_items.sum { |i| i.price * i.quantity }
    order = Order.create!(user: current_user, quantity: line_items.sum(&:quantity), total: total, delivery_address: params[:delivery_address])
    line_items.each do |i|
      OrderDetail.create!(order: order, book: i.book, count: i.quantity, price: i.price)
    end
    cart.line_items.destroy_all
    redirect_to complete_order_path(order)
  end

  def complete
    @order = Order.find(params[:id])
  end

  private

  def require_login
    redirect_to users_sign_in_path unless user_signed_in?
  end
end

ec_site/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_login

  def index
    @keyword = params[:keyword].to_s
    @tag_id = params[:tag_id].presence
    scope = Book.where(product_display: true)
    scope = scope.where("book_name LIKE ?", "%#{@keyword}%") if @keyword.present?
    if @tag_id.present?
      scope = scope.joins(:taggings).where(taggings: { tag_id: @tag_id })
    end
    @books = scope.order(:id)
    @tags = Tag.order(:id)
  end

  def show
    @book = Book.find(params[:id])
  end

  private

  def require_login
    redirect_to users_sign_in_path unless user_signed_in?
  end
end

ec_site/app/helpers/admins/books_helper.rb
module Admins::BooksHelper
end

ec_site/app/helpers/admins/tags_helper.rb
module Admins::TagsHelper
end

ec_site/app/helpers/application_helper.rb
module ApplicationHelper
end

ec_site/app/helpers/carts_helper.rb
module CartsHelper
end

ec_site/app/helpers/orders_helper.rb
module OrdersHelper
end

ec_site/app/helpers/products_helper.rb
module ProductsHelper
end

ec_site/app/helpers/users/mypages_helper.rb
module Users::MypagesHelper
end

ec_site/app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

ec_site/app/views/admins/books/create.html.erb
<h1>Admins::Books#create</h1>
<p>Find me in app/views/admins/books/create.html.erb</p>

ec_site/app/views/admins/books/destroy.html.erb
<h1>Admins::Books#destroy</h1>
<p>Find me in app/views/admins/books/destroy.html.erb</p>

ec_site/app/views/admins/books/edit.html.erb
<h2>書籍編集</h2>
<%= form_with model: @book, url: admins_book_path(@book), method: :patch, html: { multipart: true }, local: true do |f| %>
  <div class="field"><%= f.file_field :image %></div>
  <div class="field">書籍名<br><%= f.text_field :book_name %></div>
  <div class="field">著者名<br><%= f.text_field :author_name %></div>
  <div class="field">発行日<br><%= f.date_select :issue_date %></div>
  <div class="field">商品表示<br><%= f.check_box :product_display %></div>
  <div class="field">価格<br><%= f.number_field :price %></div>
  <div class="field">タグ<br>
    <% @tags.each do |t| %>
      <label><%= check_box_tag "book[tag_ids][]", t.id, @book.tags.exists?(t.id) %> <%= t.tag_name %></label>
    <% end %>
  </div>
  <div class="field">ステータス<br><%= f.text_field :status %></div>
  <%= f.submit "更新" %>
<% end %>
<%= link_to "書籍詳細へ戻る", admins_book_path(@book) %> |
<%= link_to "一覧へ戻る", admins_books_path %>

ec_site/app/views/admins/books/index.html.erb
<h2>書籍一覧</h2>
<%= link_to "新規書籍", new_admins_book_path %> |
<%= link_to "新規タグ", new_admins_tag_path %> |
<%= link_to "タグ一覧", admins_tags_path %> |
<%= link_to "ログアウト", admins_sign_out_path, data: { turbo_method: :delete } %>
<hr>
<% @books.each do |b| %>
  <% if b.image.attached? %>
    <%= image_tag b.image.variant(resize_to_limit: [140,140]) %>
  <% end %>
  <p>書籍名：<%= b.book_name %></p>
  <p>著者名：<%= b.author_name %></p>
  <p>発行日：<%= b.issue_date %></p>
  <p>商品表示：<%= b.product_display ? "true" : "false" %></p>
  <p>価格：<%= number_to_currency(b.price, unit: "¥", precision: 0) %></p>
  <p>ステータス：<%= b.status %></p>
  <%= link_to "書籍詳細", admins_book_path(b) %>
  <hr>
<% end %>

ec_site/app/views/admins/books/new.html.erb
<h2>書籍新規登録</h2>
<%= form_with model: @book, url: admins_books_path, html: { multipart: true }, local: true do |f| %>
  <div class="field"><%= f.file_field :image %></div>
  <div class="field">書籍名<br><%= f.text_field :book_name %></div>
  <div class="field">著者名<br><%= f.text_field :author_name %></div>
  <div class="field">発行日<br><%= f.date_select :issue_date %></div>
  <div class="field">商品表示<br><%= f.check_box :product_display %></div>
  <div class="field">価格<br><%= f.number_field :price %></div>
  <div class="field">タグ<br>
    <% @tags.each do |t| %>
      <label><%= check_box_tag "book[tag_ids][]", t.id %> <%= t.tag_name %></label>
    <% end %>
  </div>
  <div class="field">ステータス<br><%= f.text_field :status %></div>
  <%= f.submit "登録" %>
<% end %>

ec_site/app/views/admins/books/show.html.erb
<% if @book.image.attached? %>
  <%= image_tag @book.image.variant(resize_to_limit: [180,180]) %>
<% end %>
<p>書籍名：<%= @book.book_name %></p>
<p>著者名：<%= @book.author_name %></p>
<p>発行日：<%= @book.issue_date %></p>
<p>商品表示：<%= @book.product_display ? "true" : "false" %></p>
<p>価格：<%= number_to_currency(@book.price, unit: "¥", precision: 0) %></p>
<p>ステータス：<%= @book.status %></p>
<p>タグ名：<%= @book.tags.pluck(:tag_name).join("、") %></p>
<%= link_to "編集", edit_admins_book_path(@book) %> |
<%= button_to "削除", admins_book_path(@book), method: :delete, data: { turbo_confirm: "削除しますか？" } %>

ec_site/app/views/admins/books/update.html.erb
<h1>Admins::Books#update</h1>
<p>Find me in app/views/admins/books/update.html.erb</p>